# NullAttributeRemover Configuration
# ----------------------------------
# Controls how the plugin handles invalid attribute modifiers

silent-mode: false  # Suppress all logs unless critical
log-when-clean: true  # Log a message even if no bad attributes were found
kick-on-failure: true  # Kick the player if a modifier couldn't be removed
logUUIDLikeNames: true  # Should any UUIDs that look like names be logged?
log-invalid-uuid-names: true  # If false, suppress logs like "Skipped bad UUID: armor.boots"
ignoreDuplicateUUIDsAcrossAttributes: false  # If true, allows modifiers with the same UUID across multiple attributes
debugLogs: false  # Enable detailed internal debug logs